# NumPy Indexing, Slicing and Filtering

- Learn how to access and modify elements in one-dimensional, two-dimensional, and three-dimensional arrays.
- Understand slicing, fancy indexing, and boolean masking.
- Load data from external files and filter data using conditions.
- Practice creating patterns using array indexing and assignment.

## Accessing Elements in a One-Dimensional Array

- Access elements using positive and negative indices.
- Retrieve individual values from different positions in the array.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2])
print(arr[-2])

3
8


## Slicing a One-Dimensional Array

- Extract portions of an array using start, stop, and step values.
- Reverse an array using negative step size.

In [3]:
print(arr[1:5])
print(arr[1:7:2])
print(arr[3:])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[2 3 4 5]
[2 4 6]
[4 5 6 7 8 9]
[1 2 3 4]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


## Fancy Indexing

- Select multiple elements from different positions in an array.
- Pass a list of indices to retrieve non-consecutive elements.

In [4]:
print(arr[[1,4,7]])

[2 5 8]


## Fancy Indexing in a Two-Dimensional Array

- Select specific rows, columns, and individual elements using advanced indexing techniques.

In [5]:
arr2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])

print(arr2[2:4 , 0:2])
print(arr2[[0,1,2,3], [1,2,3,4]])
print(arr2[[0,4,5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]


## Boolean Masking

- Filter array elements based on specific conditions.
- Return only the values that satisfy the given condition.

In [6]:
print(arr[arr > 4])

[5 6 7 8 9]


## Loading Data from a File

- Use genfromtxt() to load numerical data from a text file.
- Specify the delimiter used in the file.

In [7]:
file_data = np.genfromtxt('data.txt', delimiter=',')

print(file_data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


## Filtering Data Using Conditions

- Create boolean arrays based on comparison operators.
- Extract values that satisfy a condition.

In [8]:
print(file_data > 50)
print(file_data[file_data > 50])

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196.  75. 766.  75.  55. 999.  78.  76.  88.]


## Using any() and all() Functions

- any() returns True if at least one value satisfies the condition.
- all() returns True only if every value satisfies the condition.
- Apply these checks row-wise or column-wise using the axis parameter.

In [9]:
print(np.any(file_data > 50, axis=1))
print(np.any(file_data > 50, axis=0))

print(np.all(file_data > 50, axis=1))
print(np.all(file_data > 50, axis=0))

[ True  True  True]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False]
[False False False False  True False False False False False False False
 False False False False False False]


## Combining Multiple Conditions

- Use logical operators to create complex filtering conditions.
- Use the tilde operator (~) to invert a boolean condition.

In [10]:
print((file_data > 30) & (file_data < 80))
print(~((file_data > 30) & (file_data < 80)))

[[False False False False False  True False False  True False False False
  False False False False False False]
 [False  True False  True False  True False  True False False False False
  False False False False False False]
 [False False  True False False False False False  True False False False
  False False False False  True False]]
[[ True  True  True  True  True False  True  True False  True  True  True
   True  True  True  True  True  True]
 [ True False  True False  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True False  True  True  True
   True  True  True  True False  True]]


## Accessing Elements in a Two-Dimensional Array

- Access individual elements, rows, and columns using row and column indices.

In [11]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

print(a)

print(a[1,5])
print(a[0,1:6:2])

print(a[0,:])

print(a[:,2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[2 4 6]
[1 2 3 4 5 6 7]
[ 3 10]


## Modifying Elements, Rows, and Columns

- Update individual elements.
- Replace entire rows and columns with new values.

In [12]:
a[1,5] = 20

print(a)

a[0,:] = [11,22,33,44,55,66,77]
a[1,:] = 100

print(a)

a[:,5] = [66,1313]
a[:,4] = 100

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 11  22  33  44  55  66  77]
 [100 100 100 100 100 100 100]]
[[  11   22   33   44  100   66   77]
 [ 100  100  100  100  100 1313  100]]


## Working with Three-Dimensional Arrays

- Access and modify elements in multi-dimensional arrays.
- Retrieve specific layers, rows, and columns.

In [13]:
b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(b)

print(b[0,1,1])

print(b[:,1,:])

print(b[:,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[3 4]
 [7 8]]
[3 7]


## Modifying Values in a Three-Dimensional Array

- Replace selected sections of a three-dimensional array using slicing.

In [14]:
b[:,1,:] = [[33,44],[77,88]]

print(b)

[[[ 1  2]
  [33 44]]

 [[ 5  6]
  [77 88]]]


## Creating a Custom Array Pattern

- Generate the following pattern using NumPy array creation, slicing, and assignment operations.

|   |   |   |   |   |
|---|---|---|---|---|
| 1 | 1 | 1 | 1 | 1 |
| 1 | 0 | 0 | 0 | 1 |
| 1 | 0 | 9 | 0 | 1 |
| 1 | 0 | 0 | 0 | 1 |
| 1 | 1 | 1 | 1 | 1 |

- Create a larger array of ones.
- Create a smaller array of zeros.
- Place the smaller array inside the larger array.
- Update the center element with the value 9.

In [15]:
arr = np.ones((5,5))

temp = np.zeros((3,3))

temp[1,1] = 9

arr[1:4,1:4] = temp

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
