# NumPy Array Initialization

- Learn how to create NumPy arrays filled with zeros, ones, custom values, and random numbers.
- Understand how to generate identity matrices and numerical sequences.
- Explore different array initialization techniques commonly used in data science and machine learning.

## Creating Arrays Filled with Zeros

- Use zeros() to create arrays where all elements are initialized to zero.
- Arrays can be created in one, two, or multiple dimensions.

In [1]:
import numpy as np

In [2]:
print(np.zeros(3))
print(np.zeros((2,3)))
print(np.zeros((2,3,4)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Creating Arrays Filled with Ones

- Use ones() to create arrays where all elements are initialized to one.
- A custom data type can also be specified.

In [3]:
print(np.ones(3))
print(np.ones((2,3)))
print(np.ones((2,3,4), dtype='int16'))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


## Creating an Identity Matrix

- Use identity() to create a square matrix with ones on the main diagonal and zeros elsewhere.

In [4]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Creating Arrays with Custom Values

- Use full() to create arrays filled with a specific value.
- Custom arrays can also be used as the fill value.

In [5]:
print(np.full((2,2), 99))
print(np.full((2,2), [[1,2], [3,4]]))

[[99 99]
 [99 99]]
[[1 2]
 [3 4]]


## Creating Arrays Based on the Shape of Another Array

- Use full() with shape information from an existing array.
- Use full_like() to create a new array with the same shape as an existing array.

In [6]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

print(np.full(a.shape,39))
print(np.full_like(a,39))

[[39 39 39 39 39 39 39]
 [39 39 39 39 39 39 39]]
[[39 39 39 39 39 39 39]
 [39 39 39 39 39 39 39]]


## Creating a Sequence of Numbers in a NumPy Array

- Use arange() to generate evenly spaced values within a specified range.
- The step value controls the increment between consecutive numbers.

In [7]:
print(np.arange(1,10,2))

[1 3 5 7 9]


## Creating Evenly Spaced Values Between Two Numbers in a NumPy Array

- Use linspace() to generate a specified number of evenly distributed values between two numbers.

In [8]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Generating Random Decimal Numbers

- Use rand() to create arrays containing random decimal values between 0 and 1.
- Use random_sample() to generate random values based on the shape of an existing array.

In [9]:
print(np.random.rand(2,4))
print(np.random.random_sample(a.shape))

[[0.96865891 0.49712774 0.55450325 0.18614077]
 [0.86420138 0.22911383 0.84102844 0.57968567]]
[[0.8786504  0.45257844 0.2165708  0.413591   0.74344451 0.41169728
  0.65209617]
 [0.8828335  0.29321765 0.66622495 0.87493854 0.2041306  0.85181738
  0.05984791]]


## Generating Random Integer Numbers

- Use randint() to generate random integers within a specified range.
- The size parameter defines the shape of the resulting array.

In [10]:
print(np.random.randint(4,7,size=(2,3)))

[[4 4 5]
 [4 6 6]]
