# NumPy Broadcasting and Vectorization

- Learn how NumPy automatically expands smaller arrays during arithmetic operations.
- Understand scalar and vector broadcasting.
- Explore vectorization for performing operations on entire arrays without loops.
- Improve code efficiency and readability using NumPy's built-in capabilities.

## Scalar Broadcasting

- Scalar broadcasting occurs when a single value is used in an operation with an array.
- NumPy automatically applies the scalar value to every element of the array.

In [2]:
import numpy as np

In [3]:
arr = np.array([100,200,300])

result = arr * 2

print(result)

[200 400 600]


## Practical Example of Scalar Broadcasting

- Apply a percentage discount to all prices in an array.
- NumPy automatically broadcasts the scalar discount value across every element.

In [4]:
prices = np.array([100,200,300])

discount = 10

final_prices = prices - (prices * discount/100)

print(final_prices)

[ 90. 180. 270.]


## Vector Broadcasting

- Vector broadcasting occurs when a one-dimensional array is combined with a two-dimensional array.
- NumPy automatically expands the vector to match the dimensions of the matrix.
- This allows element-wise operations without manual repetition.

In [5]:
matrix = np.array([[1,2,3], [4,5,6]])

vector = np.array([100,200,300])

result = matrix + vector

print(result)

[[101 202 303]
 [104 205 306]]


## Vectorization

- Vectorization allows operations to be performed on entire arrays at once.
- It eliminates the need for explicit loops.
- Vectorized operations are faster and more efficient than traditional looping approaches.

In [6]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

result = arr1 + arr2

print(result)

[5 7 9]


In [7]:
arr = np.array([100,200,300])

multiplied = arr * 3

print(multiplied)

[300 600 900]
