# NumPy Array Manipulation

- Learn how to insert, append, concatenate, and delete elements in NumPy arrays.
- Perform manipulation operations on both one-dimensional and two-dimensional arrays.
- Understand the role of the axis parameter in array operations.

## Inserting Elements into Arrays

- Use insert() to add values at a specific index.
- axis=0 inserts rows.
- axis=1 inserts columns.
- axis=None flattens the array before insertion.

In [1]:
import numpy as np

In [2]:
# 1-D ARRAY

arr_1d = np.array([56,34,23,78,54,10])

print(arr_1d)

new_arr_1d = np.insert(arr_1d,2,100)

print(new_arr_1d)

[56 34 23 78 54 10]
[ 56  34 100  23  78  54  10]


## Inserting Rows and Columns into a Two-Dimensional Array

- Insert a row at a specific position.
- Insert a column at a specific position.
- Insert values into the flattened version of an array.

In [3]:
# 2-D ARRAY

arr_2d = np.array([[1,2], [3,4]])

print(arr_2d)

row_arr_2d = np.insert(arr_2d,1,[5,6],axis=0)

print(row_arr_2d)

col_arr_2d = np.insert(arr_2d,1,[5,6],axis=1)

print(col_arr_2d)

new_arr_2d = np.insert(arr_2d,1,[100,500],axis=None)

print(new_arr_2d)

[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]
[  1 100 500   2   3   4]


## Appending Elements to Arrays

- Use append() to add elements at the end of an array.
- For one-dimensional arrays, values are added to the last position.

In [4]:
# 1-D ARRAY

arr_1d = np.array([1,2,3])

print(arr_1d)

new_arr = np.append(arr_1d,[7,8])

print(new_arr)

[1 2 3]
[1 2 3 7 8]


## Appending Rows and Columns to a Two-Dimensional Array

- Append a new row at the end of the array.
- Append a new column at the end of the array.
- Use axis=None to flatten the array before appending.

In [5]:
# 2-D ARRAY

arr_2d = np.array([[1,2], [3,4]])

print(arr_2d)

row_arr_2d = np.append(arr_2d,[[5,6]],axis=0)

print(row_arr_2d)

col_arr_2d = np.append(arr_2d,[[5],[6]],axis=1)

print(col_arr_2d)

new_arr_2d = np.append(arr_2d,[[100,500]],axis=None)

print(new_arr_2d)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[  1   2   3   4 100 500]


## Concatenating Arrays

- Use concatenate() to merge multiple arrays.
- Arrays can be merged horizontally, vertically, or after flattening.

In [6]:
# 1-D ARRAY

arr1_1d = np.array([1,2,3])
arr2_1d = np.array([4,5,6])

print(arr1_1d)
print(arr2_1d)

new_arr_1d = np.concatenate((arr1_1d,arr2_1d))

print(new_arr_1d)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


## Concatenating Two-Dimensional Arrays

- Use axis=1 for horizontal concatenation.
- Use axis=0 for vertical concatenation.
- Use axis=None to flatten both arrays before merging.

In [7]:
# 2-D ARRAY

arr1_2d = np.array([[1,2], [3,4]])
arr2_2d = np.array([[5,6], [7,8]])

print(arr1_2d)
print(arr2_2d)

col_arr_2d = np.concatenate((arr1_2d,arr2_2d),axis=1)

print(col_arr_2d)

row_arr_2d = np.concatenate((arr1_2d,arr2_2d),axis=0)

print(row_arr_2d)

new_arr_2d = np.concatenate((arr1_2d,arr2_2d),axis=None)

print(new_arr_2d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


## Deleting Elements from Arrays

- Use delete() to remove values at a specific index.
- For one-dimensional arrays, the selected element is removed.

In [8]:
# 1-D ARRAY

arr_1d = np.array([56,34,23,78,54,10])

print(arr_1d)

new_arr_1d = np.delete(arr_1d,2)

print(new_arr_1d)

[56 34 23 78 54 10]
[56 34 78 54 10]


## Deleting Rows and Columns from a Two-Dimensional Array

- Use axis=0 to delete rows.
- Use axis=1 to delete columns.
- Use axis=None to flatten the array before deletion.

In [9]:
# 2-D ARRAY

arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr_2d)

row_arr_2d = np.delete(arr_2d,1,axis=0)

print(row_arr_2d)

col_arr_2d = np.delete(arr_2d,1,axis=1)

print(col_arr_2d)

new_arr_2d = np.delete(arr_2d,1,axis=None)

print(new_arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
[1 3 4 5 6 7 8 9]
