# NumPy Repeating and Copying Arrays

- Learn how to repeat elements in NumPy arrays.
- Understand how the axis parameter affects repetition.
- Learn how to create an independent copy of an array.
- Explore the difference between modifying an original array and its copy.

## Repeating Elements in a One-Dimensional Array

- Use repeat() to repeat each element of an array a specified number of times.
- The repeated values are returned in a new array.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

r1 = np.repeat(arr1,3)

print(r1)

[1 1 1 2 2 2 3 3 3]


## Repeating Elements in a Two-Dimensional Array

- Use axis=1 to repeat elements horizontally across columns.
- Use axis=0 to repeat elements vertically across rows.
- Use axis=None to flatten the array before repeating its elements.

In [3]:
arr2 = np.array([[1,2,3], [4,5,6]])

r2 = np.repeat(arr2,3,axis=1)          # REPEATS HORIZONTALLY
r3 = np.repeat(arr2,3,axis=0)          # REPEATS VERTICALLY
r4 = np.repeat(arr2,3,axis=None)       # FLATTENS THE ARRAY AND THEN REPEATS

print(r2)
print(r3)
print(r4)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


## Creating a Copy of an Array

- Use copy() to create an independent copy of an array.
- Changes made to the copied array do not affect the original array.

In [4]:
a = np.array([1,2,3])

b = a.copy()

b[0] = 11

print(a)
print(b)

[1 2 3]
[11  2  3]
