# NumPy Mathematics, Linear Algebra, and Statistics

- Learn how to perform mathematical operations on NumPy arrays.
- Apply trigonometric functions to array elements.
- Explore common linear algebra operations such as matrix multiplication, determinant, inverse, and trace.
- Use statistical and aggregate functions to analyze numerical data.

## Mathematical Operations on Arrays

- Perform arithmetic operations directly on NumPy arrays.
- NumPy applies operations element-wise to all values in the array.

In [1]:
import numpy as np

In [2]:
a = np.array([2,4,6,8,10])

print("a =", a)
print("a + 2 =", a + 2)
print("a - 2 =", a - 2)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a ** 2 =", a ** 2)

a = [ 2  4  6  8 10]
a + 2 = [ 4  6  8 10 12]
a - 2 = [0 2 4 6 8]
a * 2 = [ 4  8 12 16 20]
a / 2 = [1. 2. 3. 4. 5.]
a ** 2 = [  4  16  36  64 100]


## Array-to-Array Arithmetic Operations

- Perform element-wise operations between arrays of the same shape.
- Corresponding elements from each array are combined.

In [3]:
b = np.array([1,2,3,4,5])

print("b =", b)
print("a + b =", a + b)

b = [1 2 3 4 5]
a + b = [ 3  6  9 12 15]


## Trigonometric Functions

- Apply trigonometric functions to every element of an array.
- NumPy performs the calculations element-wise.

In [4]:
print(np.sin(a))
print(np.cos(a))

[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153]


## Matrix Multiplication

- Use matmul() to perform matrix multiplication.
- The number of columns in the first matrix must match the number of rows in the second matrix.

In [5]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


## Determinant of a Matrix

- The determinant is a scalar value associated with a square matrix.
- It is commonly used in linear algebra to determine matrix properties.

In [6]:
c = np.identity(3)

d = np.array([
    [11,2,3],
    [4,15,16],
    [17,8,19]
])

print(np.linalg.det(c))
print(np.linalg.det(d))

1.0
1450.0


## Inverse of a Matrix

- Use inv() to calculate the inverse of a square matrix.
- A matrix must be non-singular to have an inverse.

In [7]:
f = np.array([
    [11,2,3],
    [4,15,16],
    [17,8,19]
])

print(np.linalg.inv(f))

[[ 0.10827586 -0.00965517 -0.00896552]
 [ 0.13517241  0.10896552 -0.11310345]
 [-0.1537931  -0.03724138  0.10827586]]


## Trace of a Matrix

- The trace of a matrix is the sum of its main diagonal elements.
- Use trace() to calculate this value.

In [8]:
t = np.array([
    [11,2,3],
    [4,15,16],
    [17,8,19]
])

print(np.trace(t))

45


## Statistical and Aggregate Functions

- Use aggregate functions to summarize numerical data.
- Common measures include minimum, maximum, mean, sum, standard deviation, and variance.

In [9]:
stats = np.array([
    [1,2,3],
    [4,5,6]
])

print(stats)

print("MAX =", np.min(stats))
print("MIN =", np.max(stats))
print("MEAN/AVERAGE =", np.mean(stats))
print("SUM =", np.sum(stats))
print("STANDARD DEVIATION =", np.std(stats))
print("VARIANCE =", np.var(stats))

[[1 2 3]
 [4 5 6]]
MAX = 1
MIN = 6
MEAN/AVERAGE = 3.5
SUM = 21
STANDARD DEVIATION = 1.707825127659933
VARIANCE = 2.9166666666666665


## Row-Wise and Column-Wise Operations

- Use the axis parameter to perform calculations across rows or columns.
- axis=0 performs column-wise operations.
- axis=1 performs row-wise operations.

In [10]:
print("ROW-WISE MAX =", np.max(stats, axis=1))
print("COLUMN-WISE MAX =", np.max(stats, axis=0))

print("ROW-WISE MIN =", np.min(stats, axis=1))
print("COLUMN-WISE MIN =", np.min(stats, axis=0))

print("ROW-WISE SUM =", np.sum(stats, axis=1))
print("COLUMN-WISE SUM =", np.sum(stats, axis=0))

ROW-WISE MAX = [3 6]
COLUMN-WISE MAX = [4 5 6]
ROW-WISE MIN = [1 4]
COLUMN-WISE MIN = [1 2 3]
ROW-WISE SUM = [ 6 15]
COLUMN-WISE SUM = [5 7 9]
