# NumPy Array Reshaping and Flattening

- Learn how to reorganize the structure of NumPy arrays.
- Understand how reshape() changes the dimensions of an array.
- Learn different ways to convert multi-dimensional arrays into one-dimensional arrays.
- Explore the difference between ravel() and flatten().

## Reshaping Arrays

- Use reshape() to change the dimensions of an array without changing its data.
- reshape() returns a view of the original array, so modifications can affect the original array.

In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3,4], [5,6,7,8]])

print(before)

after = before.reshape(8,1)
print(after)

after = before.reshape(4,2)
print(after)

after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening Arrays with ravel()

- Use ravel() to convert a multi-dimensional array into a one-dimensional array.
- ravel() returns a view of the original array.
- Changes made to the returned array can affect the original array.

In [3]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.ravel())

[1 2 3 4 5 6]


## Flattening Arrays with flatten()

- Use flatten() to convert a multi-dimensional array into a one-dimensional array.
- flatten() returns a copy of the original array.
- Changes made to the returned array do not affect the original array.

In [4]:
print(arr.flatten())

[1 2 3 4 5 6]
