# NumPy Stacking and Splitting Arrays

- Learn how to combine multiple NumPy arrays into a single array.
- Understand vertical and horizontal stacking operations.
- Learn how to split one-dimensional and two-dimensional arrays into equal parts.

## Vertical Stacking of Arrays

- Use vstack() to merge arrays vertically.
- Arrays are stacked row-wise, increasing the number of rows.

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack((v1,v2)))
print(np.vstack((v1,v2,v1,v2)))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


## Horizontal Stacking of Arrays

- Use hstack() to merge arrays horizontally.
- Arrays are joined column-wise, increasing the number of columns.

In [3]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## Splitting a One-Dimensional Array

- Use split() to divide an array into equal parts.
- The number of sections must evenly divide the array.

In [4]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]


## Horizontal Splitting of a Two-Dimensional Array

- Use hsplit() to divide a two-dimensional array column-wise.
- Each split contains a subset of the original columns.

In [5]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

print(np.hsplit(arr2,2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


## Vertical Splitting of a Two-Dimensional Array

- Use vsplit() to divide a two-dimensional array row-wise.
- Each split contains a subset of the original rows.

In [6]:
print(np.vsplit(arr2,2))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
