# NumPy Handling Missing and Infinite Values

- Learn how to detect missing values in NumPy arrays.
- Understand how to replace missing values with custom values.
- Learn how to identify positive and negative infinite values.
- Replace infinite values to prepare data for analysis and machine learning tasks.

## Detecting Missing Values with isnan()

- Use isnan() to identify missing values in an array.
- The function returns True where a missing value (NaN) is present.
- NaN stands for Not a Number.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,np.nan,3,4,np.nan,5])

print(np.isnan(arr))

[False False  True False False  True False]


## Replacing Missing Values with nan_to_num()

- Use nan_to_num() to replace missing values in an array.
- By default, NaN values are replaced with 0.
- A custom replacement value can also be specified.

In [3]:
cleaned_arr1 = np.nan_to_num(arr)
print(cleaned_arr1)

cleaned_arr2 = np.nan_to_num(arr, nan=100)
print(cleaned_arr2)

[1. 2. 0. 3. 4. 0. 5.]
[  1.   2. 100.   3.   4. 100.   5.]


## Detecting Infinite Values with isinf()

- Use isinf() to identify positive and negative infinite values.
- The function returns True where an infinite value is present.

In [4]:
arr = np.array([1,2,np.inf,3,4,-np.inf,5])

print(np.isinf(arr))

[False False  True False False  True False]


## Replacing Infinite Values with nan_to_num()

- Use nan_to_num() to replace positive and negative infinite values.
- Specify custom values using the posinf and neginf parameters.

In [5]:
cleaned_arr = np.nan_to_num(arr, posinf=1000, neginf=-1000)

print(cleaned_arr)

[    1.     2.  1000.     3.     4. -1000.     5.]
